<?xml version="1.0"?>
<package format="2">
  <name>maze_control</name>
  <version>0.0.0</version>
  <description>The maze_control package</description>

  <maintainer email="hri25-group2@todo.todo">hri25-group2</maintainer>

  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
</package>
